name: Test python files with Pytest

on:
  push:
  pull_request:
  workflow_dispatch:  #  This enables the "Run workflow" button in GitHub Actions

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        
    - name: set up coverage option
      uses: SASP2025/actions-example/.github/jobs/pytest@add-example
      with:
       coverage: true
       coverage-target: exercise_package
       
    - name: Run tests
      run: |
        pytest
