
name: Test Python files with Pytest

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  test:
    uses: SASP2025/actions-example/.github/workflows/reusable_pytest.yml@d4f5274d1207eacc40b38ecc326f39d3e35223ca
    with:
      coverage: true
      coverage-target: exercise_package
