
name: Test Python files with Pytest

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[tests]

      - name: Run Pytest Composite Action
        uses: SASP2025/actions-example/.github/jobs/pytest@main   #calls the composite action from another repo
        with:
          coverage: true
          coverage-target: exercise_package
